# Generated by Django 5.2.7 on 2025-11-03 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='certifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=200)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('certificate_name', models.CharField(help_text='e.g Course Completion Certificate', max_length=200)),
                ('course_name', models.CharField(blank=True, max_length=200, null=True)),
                ('completion_date', models.DateTimeField(auto_now_add=True)),
                ('issued_by', models.CharField(max_length=200)),
                ('issued_date', models.DateTimeField(auto_now=True)),
                ('certificate_number', models.CharField(editable=False, max_length=100, unique=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userinfo')),
            ],
            options={
                'ordering': ['-issued_date'],
            },
        ),
    ]
